# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto21
#   #   commands:
#   #     - echo Installing Maven...
#   # pre_build:
#   #   commands:
#   #     - echo Logging in to Docker hub...
#   #     - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#   build:
#     commands:
#       - echo Building, Testing and packaging the application...
#       - mvn package
#   post_build:
#     commands:
#       - echo Build, Testing and packaging completed.
# artifacts:
#   files:
#     - App/target/*.jar
#     # - target/*.jar
#   discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'



# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto21
#   pre_build:
#     commands:
#       - echo Changing directory to App...
#       - cd /codebuild/output/src1251549355/src/App
#   build:
#     commands:
#       - echo Building, Testing and packaging the application...
#       - mvn clean package
#   post_build:
#     commands:
#       - echo Build, Testing and packaging completed.
# artifacts:
#   files:
#     - /codebuild/output/src1251549355/src/App/target/*.jar
#   discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'




version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Building, Testing, and packaging the application...
      - cd App  # Navigate to the correct directory
      - mvn clean package  # Clean and build the project
  post_build:
    commands:
      - echo Build, Testing, and packaging completed.
artifacts:
  files:
    - App/target/*.jar  # Ensure this path is correct after build
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

