
# this .yml file works successfully

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Building, Testing, and packaging the application...
      - cd App  # Navigate to the correct directory
      - mvn clean package  # Clean and build the project
  post_build:
    commands:
      - echo Build, Testing, and packaging completed.
artifacts:
  files:
    - App/target/*.jar  # Ensure this path is correct after build
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

